apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sopes
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-node
          image: osmarsantizo/apifront
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: sopes
spec:
  selector:
    app: api
  ports:
    - name: api-node
      port: 3001
      targetPort: 3001
  type: LoadBalancer
